name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t techsoland:latest .

    - name: Tag Docker image
      run: |
        REPOSITORY_URI=472462225461.dkr.ecr.$AWS_REGION.amazonaws.com/techsoland
        docker tag techsoland:latest $REPOSITORY_URI:latest

    - name: Push Docker image to ECR
      run: |
        REPOSITORY_URI=472462225461.dkr.ecr.$AWS_REGION.amazonaws.com/techsoland
        docker push $REPOSITORY_URI:latest
